apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: yyy
  namespace: default
  labels:
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: true
  git:
    branch: main
    directory: /
    repo: http://gitea-http.gitea.svc.cluster.local:3000/nephio/yyy.git
    secretRef:
      name: yyy-access-token-porch
  type: git
