apiVersion: req.nephio.org/v1alpha1
kind: DataNetwork
metadata:
  name: internet
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.UPFDeployment.upf-example-cluster01
spec:
  networkInstance:
    name: vpc-internet
  pools:
    - name: pool1
      prefixLength: 24
status:
  pools:
    - name: pool1
      ipClaim:
        prefix: 172.0.0.0/8
