apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n4
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n4
spec:
  config: '{"cniVersion":"0.3.1","vlan":10,"plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth1","mode":"bridge","ipam":{"type":"static","addresses":[{"address":"10.0.0.10/24","gateway":"10.0.0.1"}]}},{"type":"tuning","capabilities":{"mac":true},"ipam":{}}]}'
