apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: xxx-repo
spec:
  upstream:
    package: repo
    repo: blueprint-manifests
    revision: main
  downstream:
    package: xxx-repo
    repo: mgmt
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      configMap:
        by-path: metadata.**
        by-value-regex: 'yyy(.*)'
        put-value: xxx${1}
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      configMap:
        by-path: spec.**
        by-value-regex: 'yyy(.*)'
        put-value: xxx${1}