apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ueransimgnb-regional-n3
  namespace: ueransim
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n3
spec:
  config: '{"cniVersion":"0.3.1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth1.10","mode":"bridge","ipam":{"type":"static","addresses":[{"address":"10.0.0.10/24","gateway":"10.0.0.1"}],"routes":[{"dst":"172.2.0.0/16","gw":"10.0.0.1"},{"dst":"172.3.0.0/16","gw":"10.0.0.1"}]}},{"type":"tuning","capabilities":{"mac":true},"ipam":{}}]}'
