apiVersion: req.nephio.org/v1alpha1
kind: Dependency
metadata:
  name: upf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.SMFDeployment.smf-example
    specializer.nephio.org/namespace: free5gc-cp
spec:
  packageName: free5gc-upf
  injectors:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: UPFDeployment
